# Generated by Django 3.1.2 on 2020-10-22 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256, verbose_name='Label')),
                ('type', models.CharField(choices=[('1', 'Text Area'), ('2', 'Integer'), ('3', 'DateTime'), ('4', 'Date')], max_length=2, verbose_name='Type')),
                ('default_value', models.CharField(max_length=1024, verbose_name='Default Value')),
                ('required', models.BooleanField(default=False, verbose_name='Is required')),
                ('validation', models.CharField(choices=[('1', 'Text'), ('2', 'Email'), ('3', 'Integer')], max_length=2, verbose_name='VAlidation')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
            },
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=1024, verbose_name='Value')),
                ('fields', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='mForms.fields', verbose_name='Fields')),
            ],
        ),
        migrations.AddField(
            model_name='fields',
            name='forms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='mForms.forms', verbose_name='Forms'),
        ),
    ]
