# Generated by Django 3.1.2 on 2020-10-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mForms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='type',
            field=models.CharField(choices=[('1', 'TextArea'), ('2', 'Integer'), ('3', 'DateTime'), ('4', 'Date'), ('5', 'Text')], max_length=2, verbose_name='Type'),
        ),
    ]
