# Generated by Django 3.1.2 on 2020-10-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mForms', '0002_auto_20201023_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='values',
            old_name='fields',
            new_name='form_fields',
        ),
    ]
