# Generated by Django 3.1.2 on 2020-10-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mForms', '0003_auto_20201023_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='default_value',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Default Value'),
        ),
    ]
