# Generated by Django 3.1.2 on 2020-10-27 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mForms', '0004_auto_20201023_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='type',
            field=models.CharField(choices=[('1', 'TextArea'), ('2', 'Integer'), ('3', 'DateTime'), ('4', 'Date'), ('5', 'Text'), ('6', 'Selector'), ('7', 'Email')], max_length=2, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='SendList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120, verbose_name='Email')),
                ('forms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sendlist', to='mForms.forms', verbose_name='Forms')),
            ],
            options={
                'verbose_name': 'SendList',
                'verbose_name_plural': 'SendLists',
            },
        ),
    ]
